############################################################
# Makefile for the examples
# 
# Author(s):	Anders Henja (Swedish Meteorological and Hydrological Institute, SMHI)
#
# Date:		2009-06-15
############################################################
include ../def.mk

all:

clean:
	@\rm -f *.o
	@\rm -f *~ core
	@\rm -f simple_test.hdf
	@\rm -f compound_test.hdf
	@\rm -f test_image.hdf

docs:

distclean:
	@\rm -f *.o
	@\rm -f *~ core
	@\rm -f simple_test.hdf
	@\rm -f compound_test.hdf
	@\rm -f test_image.hdf

distribution:

install:

