###########################################################################
# Copyright (C) 2009 Swedish Meteorological and Hydrological Institute, SMHI,
#
# This file is part of HLHDF.
#
# HLHDF is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HLHDF is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with HLHDF.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################

############################################################
# Makefile for generating the documentation
# 
# Author(s):	Anders Henja (Swedish Meteorological and Hydrological Institute, SMHI)
#
# Date:		2009-06-11
############################################################
include ../def.mk

all:

.PHONY: clean
clean:
	@\rm -f *.o
	@\rm -f *~

.PHONY: docs
docs:

.PHONY: distclean
distclean:
	@\rm -f *.o
	@\rm -f *~ core
	@\rm -fr doxygen

.PHONY: distribution
distribution:

.PHONY: install
install:

