############################################################
# Makefile for generating the documentation
# 
# Author(s):	Anders Henja (Swedish Meteorological and Hydrological Institute, SMHI)
#
# Date:		2009-06-11
############################################################
include ../def.mk

all:

clean:
	@\rm -f *.o
	@\rm -f *~

docs:
	@doxygen hlhdf_doxygen.cfg

distclean:
	@\rm -f *.o
	@\rm -f *~ core
	@\rm -fr doxygen

distribution:

install:

